version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bankingapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - banking-network
    volumes:
      - mysql_data:/var/lib/mysql

  banking_app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/bankingapp
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    depends_on:
      - mysql_db
    ports:
      - "8081:8080"
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  mysql_data:

